website/portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"
urlpatterns = [
    path("",views.home,name="home"),
    path("about",views.about,name="about"),
    path("contact",views.contact,name="contact"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("portfolio/",include("portfolio.urls",namespace="portfolio")),

]

website/portfolio/models.py
from django.db import models

# Create your models here.

website/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
# Create your views here.

def home(request):
    return render(request,"portfolio/home.html")
def about(request):
    return render(request,"portfolio/about.html")
def contact(request):
    return render(request,"portfolio/contact.html")

website/portfolio/templates/portfolio/about.html
{% extends "portfolio/layout.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" href="{% static 'portfolio/files/about.css' %}">
    <section class="identify">
        <div class="biography">
            <img src="{% static 'portfolio/images/myimage.jpeg' %}">
            <p class="about-me">
                I'm Tharcisse Ntirandekura, a software engineer and programmer. With a strong background in coding and a passion for creating high-quality software solutions, I am dedicated to delivering exceptional results.
            I specialize in web development, mobile app development, or data analysis. Through my experience, I have developed a deep understanding of various programming languages, including  Python, JavaScript, or Java.
            </p>
        </div>
        <div class="hobby">
            <img src="{% static 'portfolio/images/myimage.jpeg' %}">
   
        </div>
    </section>


    <!-- <img src="{% static 'portfolio/images/background.jpeg' %}"> -->

{% endblock body %}

website/portfolio/templates/portfolio/contact.html
{% extends "portfolio/layout.html" %}
{%load static%}

{% block body %}
    <link rel="stylesheet" href="{% static 'portfolio/files/contact.css' %}">
    <p class="contact">
        <h3>phone: +1 440 458 1012</h3>
        <h3>Email : tntirand@oberlin.edu</h3>
        <h3>Address: 135 W. Lorain St</h3>
        <h3>City : oberlin</h3>
        <h3>State: Ohio</h3>
        <h3>Country : United States</h3>
    </p>
{% endblock body %}

website/portfolio/templates/portfolio/home.html
{% extends "portfolio/layout.html" %}
{%load static%}
{% block body %}
    <link rel="stylesheet" href="{% static 'portfolio/files/home.css' %}">
    <section class="identify">
        <div>
            <h1>My name is Tharcisse</h1>
            <h2></h2>
        </div>
        <div class="image">
            <img src="{% static 'portfolio/images/myimage.jpeg' %}">
        </div>
    </section>

    <section class="follow">
        <span class="fa fa-facebook"></span>
        <span class="fa fa-instagram"></span>
        <span class="fa fa-github"></span>
        <span class="fa fa-linkedin"></span>
    </section>

    <style>
        .follow{
            position: absolute;
            bottom: 40%;
            left: 10%;
        }
    </style>
{% endblock body %}

website/portfolio/templates/portfolio/index.html
{% extends "portfolio/layout.html" %}
{%load static%}
{% block body %}
    <link rel="stylesheet" href="{% static 'portfolio/files/home.css' %}">
    <section class="identify">
        <div>
            <h1>My name is Tharcisse</h1>
            <h2></h2>
        </div>
        <div class="image">
            <img src="{% static 'portfolio/images/myimage.jpeg' %}">
        </div>
    </section>

    <section class="follow">
        <span class="fa fa-facebook"></span>
        <span class="fa fa-instagram"></span>
        <span class="fa fa-github"></span>
        <span class="fa fa-linkedin"></span>
    </section>

    <style>
        .follow{
            position: absolute;
            bottom: 40%;
            left: 10%;
        }
    </style>
{% endblock body %}

website/portfolio/templates/portfolio/layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My personal portfolio</title>
    <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
    <link rel="stylesheet" href="{% static 'portfolio/files/layout.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>

<body>
    <section class="nav-bar">
        <li id="about"><a href="{% url 'portfolio:about' %}">about</a></li>
        <li id="resume"><a href="#resume">resume</a></li>
        <li id="portfolio"><a href="#porfolio">porfolio</a></li>
        <li id="contact"><a href="{% url 'portfolio:contact' %}">contact</a></li>
        <li id="home"><a href="{% url 'portfolio:home' %}">home</a></li>

    </section>
    
    {% block body %}  
    {% endblock  %}
</body>
<script>
    var typed = new Typed('h2', {
    strings: ["Software engineer","computer scientist"],
    typeSpeed: 60,
    backSpeed : 60,
    loop:true
    });
</script>
</html>